apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dev-app-core-hro-ccm-backend-pipeline-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
          name: app-core-hro-ccm-backend
  params:
  - name: build-stage
    value: "dev"
  - name: git-url
    value: "https://gitlab.herosonsa.co.kr/app/core/hro-ccm-backend.git"
  - name: git-revision
    value: "dev"
  - name: git-username
    value: "tekton-dashboard"
  - name: clone-to-directory
    value: $(context.pipelineRun.name)
  - name: image-url
    value: "tbd5d1uh.private-ncr.fin-ntruss.com/app/core/hro-ccm-backend"
#  - name: argo-app-name
#    value: "core-ccm-api-dev"
  - name: gitops-url
    value: "https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git"
  - name: gitops-revision
    value: "dev"
  - name: gitops-path
    value: "app/core/hro-ccm-backend/dev"
  - name: rollout-strategy
    value: "rolling"
  - name: deploy-manifest
    value: "kustomization.yaml"
#  - name: argo-url
#    value: "argocd.herosonsa.co.kr"
  - name: sonar-project-key
    value: "core-ccm-api-dev"
  - name: pipeline-name
    value: $(context.pipelineRun.name)
  - name: mm-channel
    value: "core:hro-ccm-backend"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-app-core-hro-ccm-backend
  - name: gitops
    emptyDir: {}
  - name: manifest-dir
    emptyDir: {}



