apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: dev-app-core-hro-com-backend-proto-listener
spec:
  serviceAccountName: sa-pipeline-trigger
  triggers:
    - name: build-trigger
      interceptors:
        - name: "CEL filter: dev-temp branch only"
          ref:
            name: "cel"
          params:
          - name: "filter"
            value: "body.ref in ['refs/heads/dev-temp']"
      bindings:
        - ref: dev-app-core-hro-com-backend-proto-binding
      template:
        ref: dev-app-core-hro-com-backend-proto-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: dev-app-core-hro-com-backend-proto-binding
spec:
  params:
    - name: gitrevision
      value: $(body.after)
    - name: gitrepositoryurl
      value: $(body.project.http_url)
    - name: gitusername
      value: $(body.user_username)
    - name: project-name
      value: $(body.project.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: dev-app-core-hro-com-backend-proto-template
spec:
  params:
    - name: gitrevision
      description: The git revision
    - name: gitrepositoryurl
      description: The git repository url
    - name: gitusername
      description: The git username
    - name: project-name
      description: The project name
  resourcetemplates:     
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: dev-app-core-hro-com-backend-proto-pipeline-
        labels:
          app: devops
          build-stage: dev
      spec:
        serviceAccountName: sa-pipeline-runner
        pipelineRef:
          name: app-core-hro-com-backend-proto
        params:
        - name: build-stage
          value: "dev"
        - name: git-url
          value: $(tt.params.gitrepositoryurl)
        - name: git-revision
          value: $(tt.params.gitrevision)
        - name: git-username
          value: $(tt.params.gitusername)
        - name: clone-to-directory
          value: "$(tt.params.gitrevision)"
        - name: image-url
          value: "tbd5d1uh.private-ncr.fin-ntruss.com/app/dev/core/temp/$(tt.params.project-name)"
        - name: spring-profile
          value: "dev,redis"
        - name: gitops-url
          value: "https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git"
        - name: gitops-revision
          value: "dev"
        - name: gitops-path
          value: "app/core/$(tt.params.project-name)/dev-temp"
        - name: rollout-strategy
          value: "rolling"
        - name: deploy-manifest
          value: "kustomization.yaml"
        - name: pipelinerun-name
          value: $(context.pipelineRun.name)
        workspaces:
        - name: source
          persistentvolumeclaim:
            claimName: pvc-app-core-$(tt.params.project-name)
        - name: gitops
          emptyDir: {}
