apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hro-dev-file-copy-pipeline-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
          name: hro-dev-file-copy
  params:
  - name: git-url
    value: "https://gitlab.herosonsa.co.kr/devops-infra/file-sample.git"
  - name: git-revision
    value: "dev"
  - name: remote-ip
    value: "10.3.20.11"
  - name: remote-username
    value: "kubeadm"
  - name: remote-path
    value: "/home/kubeadm/file"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-hero-dev-build
  - name: ssh-creds
    secret:
      secretName: rsync-ssh-credentials



