apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dev-app-core-hro-frontend-pipeline-
  labels:
    app: devops
    build-stage: dev
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
          name: app-core-hro-frontend
  params:
  - name: git-url
    value: "https://gitlab.herosonsa.co.kr/app/core/hro-frontend.git"
  - name: git-revision
    value: "dev"
  - name: git-username
    value: "tekton-dashboard"
  - name: clone-to-directory
    value: $(context.pipelineRun.name)
  - name: exclude-path
    value: "--exclude='WEB-INF'"
  - name: remote-ip
    value: "10.3.20.12"
  - name: remote-path
    value: "/hro_app/app/web/DEV-BIZ-11/ncrm"
  - name: sonar-project-key
    value: "core-frontend-dev"
  - name: pipeline-name
    value: $(context.pipelineRun.name)
  - name: mm-channel
    value: "core:hro-frontend"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-app-core-hro-frontend
#  - name: ssh-creds
#    secret:
#      secretName: hro-rsync-ssh



