apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: prd-app-core-hro-frontend-deploy-pipeline-
  labels:
    app: devops
    build-stage: prd
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
          name: app-core-hro-frontend-deploy
  params:
  - name: git-username
    value: "tekton-dashboard"
  - name: clone-to-directory
    value: $(context.pipelineRun.name)
  - name: exclude-path
    value: "--exclude='WEB-INF'"
  - name: remote-ip
    value: "10.3.20.12"
  - name: remote-path
    value: "/hro_app/app/web/DEV-BIZ-11/ncrm"
  - name: pipeline-name
    value: $(context.pipelineRun.name)
  - name: mm-channel
    value: "core:hro-frontend"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-app-core-hro-frontend



