apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-result
  labels:
    app.kubernetes.io/version: "0.1"
    stage: dev
  annotations:
    tekton.dev/tags: build-tool
    tekton.dev/displayName: "print-result"
    stage: dev
spec:
  description: >-
   Print pipeline result
  params:
    - description: image name
      name: build-image
      type: string
    - description: scan-results
      name: scan-result
      type: string
  steps:
    - name: print
      #image: docker.io/library/bash:5.0.18@sha256:8ef3f8518f47caf1ddcbdf49e983a9a119f9faeb41c2468dd20ff39cd242d69d #tag: 5.0.18
      image: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/devops/library/bash:5.0.18
      script: |
        #!/usr/bin/env bash
        echo "====== Pipeline Result ====== "
        echo $(params.build-image) " pushed to registry after sonar scan " $(params.scan-result)
