---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: scp
spec:
  description: >-
        This task can be used to copy local files to remote.
  workspaces:
    - name: source
      description: The directory you want to sync.
    - name: ssh-directory
      optional: true
      description: ssh directory with private key, known_hosts, config.
  params:
    - name: remote-path
      type: string
    - name: remote-ip
      type: string
    - name: remote-username
      type: string
  steps:
    - name: scp
      image: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/devops/rsync-sshpass:hero
      env:
      - name: SSH_DIRECTORY_PATH
        value: $(workspaces.ssh-directory.path)
      workingDir: $(workspaces.source.path)
      script: |
          cp -R "${SSH_DIRECTORY_PATH}" "$HOME"/.ssh
          chmod 700 "$HOME"/.ssh
          chmod -R 400 "$HOME"/.ssh/*

          echo "local to remote"
          scp -o StrictHostKeyChecking=no -r $(workspaces.source.path)/[!.]* $(params.remote-username)@$(params.remote-ip):$(params.remote-path)/

