apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: vm-rsync-ssh
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: rsync, files sync
    tekton.dev/categories: CLI
    tekton.dev/displayName: "rsync"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  description: >-
        This task can be used to synchronize local and remote files.
  workspaces:
    - name: source
      description: The directory you want to sync.
    - name: ssh-directory
      optional: true
  params:
    - name: local-path
      type: string
    - name: remote-path
      type: string
    - name: remote-ip
      type: string
    - name: remote-username
      type: string
    - name: exclude-path
  steps:
    - name: rsync
      image: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/devops/rsync-sshpass:hero
      env:
      - name: SSH_DIRECTORY_PATH
        value: $(workspaces.ssh-directory.path)
      workingDir: $(workspaces.source.path)/$(params.local-path)
      script: |
        cp -R "${SSH_DIRECTORY_PATH}" "$HOME"/.ssh
        chmod 700 "$HOME"/.ssh
        chmod -R 400 "$HOME"/.ssh/*
        
        #mkdir ./exclude
        #mv $(params.exclude-path) ./exclude/

        rsync -azvh --exclude='.*' --exclude=$(params.exclude-path) -e "ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa -p2122" $(params.local-path)/ $(params.remote-username)@$(params.remote-ip):$(params.remote-path)/


