apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    app: devops
  name: app-core-hro-com-ncrm-deploy
spec:
  params:
    - name: build-id
    - name: username
    - name: image-url
    - name: gitops-url
    - name: gitops-revision
    - name: gitops-path
    - name: deploy-manifest
    - name: rollout-strategy
    - name: pipelinerun-name
    - name: pipeline-name
    - name: mm-channel
  workspaces:
    - name: gitops
    - name: hro-tekton-logs
  tasks:
    - name: notify-pipeline-start
      taskRef:
        name: mm-notify-start
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: username
          value: $(params.username)
        - name: CHANNEL_NAME
          value: $(params.mm-channel)
    - name: update-gitops
      taskRef:
        name: update-gitops
      runAfter:
        - notify-pipeline-start
      params:
        - name: gitops-revision
          value: $(params.gitops-revision)
        - name: deploy-manifest
          value: $(params.deploy-manifest)
        - name: gitops-path
          value: $(params.gitops-path)
        - name: gitops-url
          value: $(params.gitops-url)
        - name: rollout-strategy
          value: $(params.rollout-strategy)
        - name: image-url
          value: $(params.image-url)
        - name: build-id
          value: $(params.build-id)
      workspaces:
        - name: gitops
          workspace: gitops
  finally:
    - name: report-result
      taskRef:
        name: mm-send-result
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: username
          value: $(params.username)
        - name: CHANNEL_NAME
          value: $(params.mm-channel)
    - name: save-pipelinerun-logs
      taskRef:
        name: tekton-logging
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: pipeline-name
          value: $(params.pipeline-name)
      workspaces:
        - name: hro-tekton-logs
          workspace: hro-tekton-logs
