apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dev-app-core-hro-com-ncrm-pipeline-
  labels:
    app: devops
    build-stage: dev
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
          name: app-core-hro-com-ncrm
          #  podTemplate:
          #    imagePullSecrets:
          #      - name: hero-reg
  params:
  - name: build-stage
    value: "dev"
  - name: git-url
    value: "https://gitlab.herosonsa.co.kr/app/core/hro-com-ncrm.git"
  - name: git-revision
    value: "dev"
  - name: git-username
    value: "tekton-dashboard"
  - name: clone-to-directory
    value: $(context.pipelineRun.name)
  - name: image-url
    value: "tbd5d1uh.private-ncr.fin-ntruss.com/app/dev/core/hro-com-ncrm"
#  - name: argo-app-name
#    value: "core-com-api-dev"
  - name: gitops-url
    value: "https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git"
  - name: gitops-revision
    value: "dev"
  - name: gitops-path
    value: "app/core/hro-com-ncrm/dev"
  - name: rollout-strategy
    value: "rolling"
  - name: deploy-manifest
    value: "kustomization.yaml"
#  - name: argo-url
#    value: "argocd.herosonsa.co.kr"
  - name: sonar-project-key
    value: "core-com-ncrm-dev"
  - name: pipeline-name
    value: $(context.pipelineRun.name)
  - name: mm-channel
    #value: "hro-build:devops-sample"
    value: "core:hro-com-ncrm"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-app-core-hro-com-ncrm
  - name: gitops
    emptyDir: {}
  - name: manifest-dir
    emptyDir: {}



