apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-com-api-test
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argo-system
spec:
  # The project the application belongs to.
  project: hro-apps

  # Source of the application manifests
  source:
    repoURL: https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: test  # For Helm, this refers to the chart version.
    path: app/core/hro-com-backend/test  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
  destination:
    name: dev-cluster
    namespace: ns-app-core-test
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-com-batch-test
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argo-system
spec:
  # The project the application belongs to.
  project: hro-apps

  # Source of the application manifests
  source:
    repoURL: https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: test  # For Helm, this refers to the chart version.
    path: app/core/hro-com-batch/test  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
  destination:
    name: dev-cluster
    namespace: ns-app-core-test
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-ccm-api-test
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argo-system
spec:
  # The project the application belongs to.
  project: hro-apps

  # Source of the application manifests
  source:
    repoURL: https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: test  # For Helm, this refers to the chart version.
    path: app/core/hro-ccm-backend/test  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
  destination:
    name: dev-cluster
    namespace: ns-app-core-test
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-ccm-batch-test
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argo-system
spec:
  # The project the application belongs to.
  project: hro-apps

  # Source of the application manifests
  source:
    repoURL: https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: test  # For Helm, this refers to the chart version.
    path: app/core/hro-ccm-batch/test  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
  destination:
    name: dev-cluster
    namespace: ns-app-core-test
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-smv-api-test
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argo-system
spec:
  # The project the application belongs to.
  project: hro-apps

  # Source of the application manifests
  source:
    repoURL: https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: test  # For Helm, this refers to the chart version.
    path: app/core/hro-smv-backend/test  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
  destination:
    name: dev-cluster
    namespace: ns-app-core-test
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-sts-api-test
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argo-system
spec:
  # The project the application belongs to.
  project: hro-apps

  # Source of the application manifests
  source:
    repoURL: https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: test  # For Helm, this refers to the chart version.
    path: app/core/hro-sts-backend/test  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
  destination:
    name: dev-cluster
    namespace: ns-app-core-test
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-com-ncrm-test
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argo-system
spec:
  # The project the application belongs to.
  project: hro-apps

  # Source of the application manifests
  source:
    repoURL: https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: test  # For Helm, this refers to the chart version.
    path: app/core/hro-com-ncrm/test  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
  destination:
    name: dev-cluster
    namespace: ns-app-core-test
  syncPolicy:
    automated: {}
---

