apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: channel-mobile-api-test
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argo-system
spec:
  # The project the application belongs to.
  project: hro-apps

  # Source of the application manifests
  source:
    repoURL: https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: test  # For Helm, this refers to the chart version.
    path: app/channel/hro-mobile-backend/test  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
  destination:
    name: dev-cluster
    namespace: ns-app-channel-test
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: channel-prmadm-api-test
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argo-system
spec:
  # The project the application belongs to.
  project: hro-apps

  # Source of the application manifests
  source:
    repoURL: https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: test  # For Helm, this refers to the chart version.
    path: app/channel/hro-prmadm-backend/test  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
  destination:
    name: dev-cluster
    namespace: ns-app-channel-test
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: channel-prm-api-test
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argo-system
spec:
  # The project the application belongs to.
  project: hro-apps

  # Source of the application manifests
  source:
    repoURL: https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git  # Can point to either a Helm chart repo or a git repo.
    targetRevision: test  # For Helm, this refers to the chart version.
    path: app/channel/hro-prm-backend/test  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
  destination:
    name: dev-cluster
    namespace: ns-app-channel-test
  syncPolicy:
    automated: {}
---

