apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: prd-app-channel-hro-mobile-backend-deploy-pipeline-
  labels:
    app: devops
    build-stage: prd
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
          name: app-channel-hro-mobile-backend-deploy
  params:
  - name: git-username
    value: "tekton-dashboard"
  - name: image-url
    value: "tbd5d1uh.private-ncr.fin-ntruss.com/app/dev/channel/hro-mobile-backend"
  - name: gitops-url
    value: "https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git"
  - name: gitops-revision
    value: "main"
  - name: gitops-path
    value: "app/channel/hro-mobile-backend/main"
  - name: rollout-strategy
    value: "rolling"
  - name: deploy-manifest
    value: "kustomization.yaml"
  - name: pipeline-name
    value: $(context.pipelineRun.name)
  - name: mm-channel
    value: "chl:hro-mobile-backend"
  workspaces:
  - name: gitops
    emptyDir: {}



