apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hro-dev-file-sync
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: git-username
    - name: clone-to-directory
    - name: sonar-project-key
    - name: direction
    - name: local-path
    - name: remote-ip
    - name: remote-username
    - name: remote-path
    - name: pipeline-name
    - name: mm-channel
  workspaces:
    - name: source
    - name: ssh-creds 
  tasks:
    - name: notify-pipeline-start
      taskRef:
        name: mm-notify-start
      params:
        - name: pipeline-name
          value: $(params.pipeline-name)
        - name: git-username
          value: $(params.git-username)
        - name: CHANNEL_NAME
          value: $(params.mm-channel)
    - name: clone-sources
      taskRef:
        name: git-clone
      runAfter:
        - notify-pipeline-start
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: subdirectory
          value: $(params.clone-to-directory)
      workspaces:
        - name: output
          workspace: source
    - name: source-scan
      taskRef:
        name: sonarqube-scan
      runAfter:
        - clone-sources
      params:
        - name: SONAR_PROJECT_KEY
          value: $(params.sonar-project-key)
        - name: SOURCE_TO_SCAN
          value: $(params.clone-to-directory)
      workspaces:
        - name: source
          workspace: source
    - name: file-sync
      taskRef:
        name: rsync
      runAfter:
        - clone-sources
      params:
        - name: direction
          value: $(params.direction)
        - name: local-path
          value: $(params.local-path)
        - name: remote-ip
          value: $(params.remote-ip)
        - name: remote-username
          value: $(params.remote-username)
        - name: remote-path
          value: $(params.remote-path)
      workspaces:
        - name: source
          workspace: source
        - name: ssh-directory
          workspace: ssh-creds
  finally:
    - name: clean-workspace
      taskRef:
        name: clean-workspace
      params:
        - name: subdirectory
          value: $(params.clone-to-directory)
      workspaces:
        - name: output
          workspace: source
    - name: report-result
      taskRef:
        #name: print-result
        name: mm-send-result
      params:
        - name: pipeline-name
          value: $(params.pipeline-name)
        - name: git-username
          value: $(params.git-username)
        - name: CHANNEL_NAME
          value: $(params.mm-channel)
