- name: Install nginx
  yum:
    name:
      - nginx
    state: present

- name: Move nginx
  ini_file:
    path: /etc/nginx/nginx.conf
    section: nginx
    option: prefix
    value: /usr/local/nginx