---
apiVersion: v1
kind: Pod
metadata:
  name: jpetfile
  labels:
    msg: exceptions-file
    app: jpetfile
spec:
  containers:
  - image: ellerbrock/alpine-bash-curl-ssl:0.3.0
    name: jpetstore
    env:
    - name: EXCEPTION_URL
      value: https://gist.githubusercontent.com/jvassev/59d7616d601d9c19e23b328e591546d8/raw/22e32c7545b5f02f2df1cfaf621d91895c4d28b1/java.log
    command:
    - bash
    - -c
    - while true; do echo Tue, 01 Aug 2023 18:13:45 +0900 [ERROR] "Internal error file $((var++)) " && curl -Lsk $EXCEPTION_URL >> /var/log/jpetfile.log ; sleep 5; done
    volumeMounts:
    - mountPath: /var/log
      name: logs
  volumes:
  - name: logs
    emptyDir: {}
