apiVersion: batch/v1
kind: CronJob
metadata:
  name: pr-delete
  namespace: devops-pipelines
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - '-c'
                - |
                  echo "${config}" > config
                  cp config ~/.kube/

                  ns=devops-pipelines  
            
                  for r in $(kubectl get pipelines.tekton.dev -l app=devops -o name -n $ns | cut -d "/" -f 2);  
            
                  do tkn pr delete --label tekton.dev/pipeline=$r -n $ns --keep 1 --force -o jsonpath='{range .items[?(@.status.conditions[*].status=="True")]}';  
                  
                  echo "--- pipeline " $r " deleted ---";
                  
                  done;  
            
                  for r in $(kubectl get pipelines.tekton.dev -l app=devops -o name -n $ns | cut -d "/" -f 2);  
                  do tkn pr delete --label tekton.dev/pipeline=$r -n $ns --keep 1 --force -o jsonpath='{range .items[?(@.status.conditions[*].status=="False")]}';  
                  echo "--- pipeline " $r " deleted ---";  
                  
                  done;     
                                    
              image: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/devops/dev:v1
              imagePullPolicy: Always
              name: tkn-prunner
              envFrom:
              - secretRef:
                  name: hro-dev-config      
          dnsPolicy: ClusterFirst
          imagePullSecrets:
            - name: hero-reg
          restartPolicy: Never
          schedulerName: default-scheduler
  schedule: '*/10 * * * *'
  successfulJobsHistoryLimit: 1 
  suspend: false
