apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-core-core-front-test-vm-deploy
spec:
  params:
    - name: remote-ip
    - name: pipeline-name
  workspaces:
    - name: credentials
  tasks:
    - name: notify-pipeline-start
      taskRef:
        name: mm-notify-start
      params:
        - name: pipeline-name
          value: $(params.pipeline-name)
    - name: vm-deploy
      taskRef:
        name: vm-deploy
      params:
        - name: remote-ip
          value: $(params.remote-ip)
      workspaces:
        - name: gitops
          workspace: gitops
  finally:
    - name: report-result
      taskRef:
        #name: print-result
        name: mm-send-result
      params:
        - name: pipeline-name
          value: $(params.pipeline-name)
