apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: app-core-core-front-test-deploy-pipeline-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
    name: app-core-core-front-test-vm-deploy
  podTemplate:
    imagePullSecrets:
      - name: hero-reg
  params:
  - name: remote-ip
    value: "10.3.20.12"
  - name: pipeline-name
    value: $(context.pipelineRun.name)
  workspaces:
  - name: credentials
    secret:
      secretName: hro-vm-auth

