apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: prd-app-channel-hro-prm-frontend-podman-build-pipeline-
  labels:
    app: devops
    build-stage: prd
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
          name: app-channel-hro-prm-frontend-podman-build
  params:
  - name: build-stage
    value: "prd"
  - name: git-url
    value: "https://gitlab.herosonsa.co.kr/app/channel/hro-prm-frontend.git"
  - name: git-revision
    value: "main"
  - name: git-username
    value: "tekton-dashboard"
  - name: clone-to-directory
    value: $(context.pipelineRun.name)
  - name: image-url
    value: "tbd5d1uh.private-ncr.fin-ntruss.com/app/prd/channel/hro-prm-frontend"
  - name: pipeline-name
    value: $(context.pipelineRun.name)
  - name: mm-channel
    value: "chl:hro-prm-frontend"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-app-channel-hro-prm-frontend
  - name: manifest-dir
    emptyDir: {}



