apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: prd-app-channel-hro-prm-frontend-podman-deploy-pipeline-
  labels:
    app: devops
    build-stage: prd
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
          name: app-channel-hro-prm-frontend-podman-deploy
  params:
  - name: git-username
    value: "tekton-dashboard"
  - name: image-url
    value: "tbd5d1uh.private-ncr.fin-ntruss.com/app/prd/channel/hro-prm-frontend"
  - name: remote-ip
    value: "10.1.10.6"
  - name: application-name
    value: "channel-prm-frontend-prd"
  - name: service-port
    value: "6411:6411"
  - name: pipeline-name
    value: $(context.pipelineRun.name)
  - name: mm-channel
    value: "chl:hro-prm-frontend"
  workspaces:
  - name: credentials
    secret:
      secretName: hro-vm-auth



