apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-app-channel-hro-prm-frontend-podman-pipeline-
  labels:
    app: devops
    build-stage: test
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
          name: app-channel-hro-prm-frontend-podman-approval
  params:
  - name: build-stage
    value: "test"
  - name: git-url
    value: "https://gitlab.herosonsa.co.kr/app/channel/hro-prm-frontend.git"
  - name: git-revision
    value: "test"
  - name: git-username
    value: "tekton-dashboard"
  - name: clone-to-directory
    value: $(context.pipelineRun.name)
  - name: image-url
    value: "tbd5d1uh.private-ncr.fin-ntruss.com/app/test/channel/hro-prm-frontend"
  - name: remote-ip
    value: "10.3.10.6"
  - name: application-name
    value: "channel-prm-frontend-test"
  - name: service-port
    value: "6411:6411"
  - name: sonar-project-key
    value: "channel-prm-frontend-test"
  - name: pipeline-name
    value: $(context.pipelineRun.name)
  - name: mm-channel
    value: "chl:hro-prm-frontend"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-app-channel-hro-prm-frontend
  - name: credentials
    secret:
      secretName: hro-vm-auth
  - name: manifest-dir
    emptyDir: {}



