apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-app-channel-hro-mobile-frontend-pipeline-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
          name: app-channel-hro-mobile-frontend-approval
  params:
  - name: build-stage
    value: "test"
  - name: git-url
    value: "https://gitlab.herosonsa.co.kr/app/channel/hro-mobile-frontend.git"
  - name: git-revision
    value: "test"
  - name: git-username
    value: "tekton-dashboard"
  - name: clone-to-directory
    value: $(context.pipelineRun.name)
  - name: image-url
    value: "tbd5d1uh.private-ncr.fin-ntruss.com/app/channel/hro-mobile-frontend"
  - name: remote-ip
    value: "10.3.20.9"
  - name: application-name
    value: "channel-mobile-frontend-test"
  - name: sonar-project-key
    value: "channel-mobile-frontend-test"
  - name: pipeline-name
    value: $(context.pipelineRun.name)
  - name: mm-channel
    value: "chl:hro-mobile-frontend"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-app-channel-hro-mobile-frontend
  - name: credentials
    secret:
      secretName: hro-vm-auth
  - name: manifest-dir
    emptyDir: {}



