apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: dev-app-core-hro-test-build-listener
spec:
  serviceAccountName: sa-pipeline-trigger
  triggers:
    - name: build-trigger
      interceptors:
        - name: "CEL filter: dev branch only"
          ref:
            name: "cel"
          params:
          - name: "filter"
            value: "body.ref in ['refs/heads/dev']"
      bindings:
        - ref: dev-app-core-hro-test-build-binding
      template:
        ref: dev-app-core-hro-test-build-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: dev-app-core-hro-test-build-binding
spec:
  params:
    - name: gitrevision
      value: $(body.after)
    - name: gitrepositoryurl
      value: $(body.project.http_url)
    - name: image-name
      value: $(body.project.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: dev-app-core-hro-test-build-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository url
    - name: image-name
      description: The image name
  resourcetemplates:     
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: hro-dev-back-build-pipeline-
      spec:
        serviceAccountName: sa-pipeline-runner
        pipelineRef:
          name: hro-dev-back-build
        podTemplate:
          imagePullSecrets:
            - name: hero-reg
        params:
        - name: git-url
          value: $(tt.params.gitrepositoryurl)
        - name: git-revision
          value: $(tt.params.gitrevision)
        - name: clone-to-directory
          value: $(tt.params.gitrevision)
        - name: image-url
          value: "tbd5d1uh.private-ncr.fin-ntruss.com/app/core/hro-test"
        - name: gitops-url
          value: "https://hello-3031818.devtools.fin-ncloud.com/3031818/app-core-hro-test.git"
        - name: gitops-revision
          value: "dev"
        - name: deploy-manifest
          value: "kustomization.yaml"
        - name: gitops-path
          value: "dev"
        - name: sonar-project-key
          value: "$(tt.params.gitrevision)"
        - name: pipeline-name
          value: $(context.pipelineRun.name)
        workspaces:
        - name: source
          persistentvolumeclaim:
            claimName: pvc-hero-dev-build
        - name: gitops
          emptyDir: {}
        - name: manifest-dir
          emptyDir: {}
