apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: dev-app-core-hro-test-listener
spec:
  serviceAccountName: sa-pipeline-trigger
  triggers:
    - name: build-trigger
      interceptors:
        - name: "CEL filter: main branch only"
          ref:
            name: "cel"
          params:
          - name: "filter"
            value: "body.ref in ['refs/heads/main']"
      bindings:
        - ref: dev-app-core-hro-test-binding
      template:
        ref: dev-app-core-hro-test-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: dev-app-core-hro-test-binding
spec:
  params:
    - name: gitrevision
      value: $(body.after)
    - name: gitrepositoryurl
      value: $(body.project.http_url)
    - name: gitusername
      value: $(body.user_username)
    - name: image-name
      value: $(body.project.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: dev-app-core-hro-test-template
spec:
  params:
    - name: gitrevision
      description: The git revision
    - name: gitrepositoryurl
      description: The git repository url
    - name: gitusername
      description: The git username
    - name: image-name
      description: The image name
  resourcetemplates:     
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: dev-app-core-hro-test-pipeline-
      spec:
        serviceAccountName: sa-pipeline-runner
        pipelineRef:
          name: app-core-hro-test
        podTemplate:
          imagePullSecrets:
            - name: hero-reg
        params:
        - name: build-stage
          value: "dev"
        - name: git-url
          value: $(tt.params.gitrepositoryurl)
        - name: git-revision
          value: $(tt.params.gitrevision)
        - name: git-username
          value: $(tt.params.gitusername)
        - name: clone-to-directory
          value: "dev/$(tt.params.gitusername)"
        - name: image-url
          value: "tbd5d1uh.private-ncr.fin-ntruss.com/app/core/hro-test"
        - name: argo-app-name
          value: "dev-app-core-hro-test"
        - name: gitops-url
          value: "https://hello-3031818.devtools.fin-ncloud.com/3031818/app-core-hro-test.git"
        - name: gitops-revision
          value: "dev"
        - name: gitops-path
          value: "dev"
        - name: rollout-strategy
          value: "rolling"
        - name: deploy-manifest
          value: "kustomization.yaml"
        - name: argo-url
          value: "argocd.herosonsa.co.kr"
        - name: sonar-project-key
          value: "dev-app-core-hro-test"
        - name: pipeline-name
          value: $(context.pipelineRun.name)
        workspaces:
        - name: source
          persistentvolumeclaim:
            claimName: pvc-hero-dev-build
        - name: gitops
          emptyDir: {}
        - name: manifest-dir
          emptyDir: {}
