apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: test-app-core-hro-test-listener
spec:
  serviceAccountName: sa-pipeline-trigger
  triggers:
    - name: build-trigger
      interceptors:
        - name: "CEL filter: merge to test branch"
          ref:
            name: "cel"
          params:
          - name: "filter"
            value: "body.object_kind in ['merge_request']"
          - name: "filter"
            value: "body.object_attributes.source_branch in ['dev']"
          - name: "filter"
            value: "body.object_attributes.target_branch in ['test']"
          - name: "filter"
            value: "body.object_attributes.action in ['merge']"
      bindings:
        - ref: test-app-core-hro-test-binding
      template:
        ref: test-app-core-hro-test-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: test-app-core-hro-test-binding
spec:
  params:
    - name: gitrevision
      value: $(body.object_attributes.last_commit.id)
    - name: gitrepositoryurl
      value: $(body.project.http_url)
    - name: gitusername
      value: $(body.user.username)
    - name: image-name
      value: $(body.project.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: test-app-core-hro-test-template
spec:
  params:
    - name: gitrevision
      description: The git revision
    - name: gitrepositoryurl
      description: The git repository url
    - name: gitusername
      description: The git username
    - name: image-name
      description: The image name
  resourcetemplates:     
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: test-app-core-hro-test-pipeline-
      spec:
        serviceAccountName: sa-pipeline-runner
        pipelineRef:
          name: app-core-hro-test-approval
        podTemplate:
          imagePullSecrets:
            - name: hero-reg
        params:
        - name: build-stage
          value: "test"
        - name: git-url
          value: $(tt.params.gitrepositoryurl)
        - name: git-revision
          value: $(tt.params.gitrevision)
        - name: git-username
          value: $(tt.params.gitusername)
        - name: clone-to-directory
          value: "test/$(tt.params.gitusername)"
        - name: image-url
          value: "tbd5d1uh.private-ncr.fin-ntruss.com/app/core/hro-test"
        # name: argo-app-name
        # value: "test-app-core-hro-test"
        - name: gitops-url
          value: "https://hello-3031818.devtools.fin-ncloud.com/3031818/app-core-hro-test.git"
        - name: gitops-revision
          value: "test"
        - name: gitops-path
          value: "test"
        - name: rollout-strategy
          value: "rolling"
        - name: deploy-manifest
          value: "kustomization.yaml"
        # name: argo-url
        # value: "argocd.herosonsa.co.kr"
        # name: sonar-project-key
        # value: "test-app-core-hro-test"
        - name: pipeline-name
          value: $(context.pipelineRun.name)
        workspaces:
        - name: source
          persistentvolumeclaim:
            claimName: pvc-app-core-hro-com-backend
        - name: gitops
          emptyDir: {}
