apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    app: devops
  name: app-core-hro-test-approval
spec:
  params:
    - name: build-stage
    - name: git-url
    - name: git-revision
    - name: git-username
    - name: clone-to-directory
    - name: image-url
    - name: spring-profile
    - name: gitops-url
    - name: gitops-revision
    - name: gitops-path
    - name: deploy-manifest
    - name: rollout-strategy
    - name: pipelinerun-name
    - name: mm-channel
  workspaces:
    - name: source
    - name: gitops
    - name: manifest-dir
  tasks:
    - name: notify-pipeline-start
      taskRef:
        name: mm-notify-start
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: username
          value: $(params.git-username)
        - name: CHANNEL_NAME
          value: $(params.mm-channel)
    - name: generate-id
      taskRef:
        name: generate-build-id
      params:
        - name: base-version
          value: $(params.build-stage)
    - name: clone-sources
      taskRef:
        name: git-clone
      runAfter:
        - generate-id
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: subdirectory
          value: $(params.clone-to-directory)
      workspaces:
        - name: output
          workspace: source
    - name: build-image
      taskRef:
        name: jib-maven
      runAfter:
        - clone-sources
      params:
        - name: IMAGE
          value: $(params.image-url):$(tasks.generate-id.results.build-id)
        - name: DIRECTORY
          value: $(params.clone-to-directory)
        - name: spring-profile
          value: $(params.spring-profile)
      workspaces:
        - name: source
          workspace: source
    - name: image-scan
      taskRef:
        name: trivy-scan
      runAfter:
        - build-image
      params:
        - name: IMAGE
          value: $(params.image-url):$(tasks.generate-id.results.build-id)
      workspaces:
        - name: manifest-dir
          workspace: manifest-dir
    - name: deploy-approval-task
      taskRef:
        apiVersion: tekton.automatiko.io/v1beta1
        kind: ApprovalTask
        name: approvaltask
      runAfter:
        - build-image
      params:
        - name: pipeline
          value: "$(params.pipelinerun-name)"
        - name: description
          value: "Approval from pipeline $(params.pipelinerun-name) for test environment"
        - name: approvers
          value:
          - "john@email.com"
        - name: notifyOnSlack
          value: "corehrotest"
    - name: update-gitops
      taskRef:
        name: update-gitops
      when:
        - input: $(tasks.deploy-approval-task.results.decision)
          operator: in
          values: [ "true" ]
      runAfter:
        - deploy-approval-task
      params:
        #- name: argo-url
        #  value: $(params.argo-url) 
        - name: gitops-revision
          value: $(params.gitops-revision)
        - name: deploy-manifest
          value: $(params.deploy-manifest)
        - name: gitops-path
          value: $(params.gitops-path)
        #- name: argo-app-name
        #  value: $(params.argo-app-name)
        - name: gitops-url
          value: $(params.gitops-url)
        - name: rollout-strategy
          value: $(params.rollout-strategy)
        - name: image-url
          value: $(params.image-url)
        - name: build-id
          value: $(tasks.generate-id.results.build-id)
      workspaces:
        - name: gitops
          workspace: gitops
  finally:
    - name: clean-workspace
      taskRef:
        name: clean-workspace
      params:
        - name: subdirectory
          value: $(params.clone-to-directory)
      workspaces:
        - name: output
          workspace: source
    - name: report-result
      taskRef:
        name: mm-send-result
      params:
        - name: pipelinerun-name
          value: $(params.pipelinerun-name)
        - name: username
          value: $(params.git-username)
        - name: CHANNEL_NAME
          value: $(params.mm-channel)

