global:
  imageRegistry: "tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/devops"
  imagePullSecrets: 
    - hero-reg
service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: keycloak-dev.herosonsa.co.kr

tls:
  enabled: true
  existingSecret: "hro-tls-secret"
  usePem: true
