apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-dev
spec:
  controlNamespace: elastic-system
    #  fluentbit:
    #    extraVolumeMounts:apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-dev
spec:
  controlNamespace: elastic-system
    #  fluentbit:
    #    extraVolumeMounts:
    #    - destination: /hro/nas_dev
    #      readOnly: true
    #      source: /hro/nas_dev
    #    image:
    #      imagePullSecrets:
    #      - name: hero-reg
    #      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/fluent/fluent-bit
    #      tag: 2.1.8-mlp
    #    inputTail:
    #      Path: /hro/nas_dev/dev/hro_app/core-com-api-dev/log/*.log
    #      Path_Key: filename
    #      multiline.parser:
    #        - java
    #        - hero-multiline-parser
    #    logLevel: debug
  fluentd:
    configReloaderImage:
      imagePullSecrets:
      - name: hero-reg
      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/kube-logging/config-reloader
      tag: v0.0.5
    image:
      imagePullSecrets:
      - name: hero-reg
      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/kube-logging/fluentd
      tag: v1.15-ruby3
    logLevel: debug
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  name: logging-dev
spec:
  extraVolumeMounts:
  - destination: /hro/nas_dev
    readOnly: true
    source: /hro/nas_dev
  image:
    imagePullSecrets:
    - name: hero-reg
    repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/fluent/fluent-bit
    tag: 2.1.8-debug
  inputTail:
    Path: /hro/nas_dev/dev/hro_app/core-com-api-dev/log/*.log
    Path_Key: filename
    multiline.parser:
      - java
      - hero-multiline-parser
  customParsers: |
    [PARSER]
        Name hero-log-parser
        Format regex
        Regex ^\[(?<time>[^ ].*)\]\[(?<pid>[^ ]*)\]\s+(?<type>[A-Z]+)\s+(?<app>([a-z].*))\s+\[(?<code>[0-9]{2,4})\]-\[(?<message>.*)
        Time_key time
    [MULTILINE_PARSER]
        name          hero-multiline-parser
        type          regex
        flush_timeout 1000
        rule      "start_state"   "/^\[\d{4}-\d{2}-\d{2}\s+.*/"                         "cont"
        rule      "cont"          "^(\s+|\||[0-9]).*"                                   "cont"
        rule      "cont"          "^$"                                                  "cont"
        rule      "cont"          "^}$"                                                 "cont"
  logLevel: debug
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: clusterflow-dev
spec:
  filters:
  - detectExceptions: 
      multiline_flush_interval: "1"  
  - parser:
      reserve_data: true
      reserve_time: true
      key_name: log
      parse:
        type: regexp
        expression: ^\[(?<time>[^ ].*)\]\[(?<pid>[^ ]*)\]\s+(?<type>[A-Z]+)\s+(?<app>([a-z]|\.)*[A-Z]\w+)\s+\[(?<code>[0-9]{2,4})\]-\[(?<message>.*)
  globalOutputRefs: 
  - clusteroutput-es
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: clusteroutput-es
spec:
  elasticsearch:
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    index_name: "app-core-dev"
    include_timestamp: true
    host: elasticsearch-master.elastic-system.svc.cluster.local
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: elasticsearch-master-credentials
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    suppress_type_name: true
    user: elastic
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: clusteroutput-s3
spec:
  s3:
    aws_key_id:
      valueFrom:
        secretKeyRef:
          key: access_key_id
          name: s3-auth
    aws_sec_key:
      valueFrom:
        secretKeyRef:
          key: secret_access_key
          name: s3-auth
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    force_path_style: "true"
    path: app-log/${tag}/%Y/%m/%d/
    s3_bucket: hro-app-log
    s3_endpoint: https://kr.object.private.fin-ncloudstorage.com
    s3_region: kr-standard
