---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: "cluster-es-output"
spec:
  elasticsearch:
    host: elasticsearch-master.elastic-system
    port: 9200
    scheme: https
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: cluster-es-flow
spec:
  filters:
  - tag_normaliser: {}
  - parser:
      parse:
        type: nginx
      remove_key_name_field: true
      reserve_data: true
  globalOutputRefs:
  - cluster-es-output
  match:
  - select:
      labels:
        log: dev
