---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-dev
spec:
  controlNamespace: elastic-system
  fluentbit:
    image:
      imagePullSecrets:
      - name: hero-reg
      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/fluent/fluent-bit
      tag: 2.1.4-debug
  fluentd:
    configReloaderImage:
      imagePullSecrets:
      - name: hero-reg
      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/kube-logging/config-reloader
      tag: v0.0.5
    image:
      imagePullSecrets:
      - name: hero-reg
      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/kube-logging/fluentd
      tag: v1.15-ruby3
    logLevel: debug
---
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: HostTailer
metadata:
  name: fluent-dev
  namespace: elastic-system
spec:
  fileTailers:
  - name: error-log
    path: /hro/nas_dev/dev/hro_app/core-com-api-dev/log/core-com-api-dev-*-error.log
    disabled: false
    containerOverrides:
      image: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/fluent/fluent-bit:2.1.4-debug
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow-core-com-api-dev
  namespace: elastic-system
spec:
  filters: 
  - detectExceptions:
      multiline_flush_interval: "0.1"
  localOutputRefs:
    - output-core-com-api-dev
  match:
  - select:
      labels:
        app.kubernetes.io/name: host-tailer
  outputRefs:
    - output-core-com-api-dev
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: output-core-com-api-dev
  namespace: elastic-system
spec:
  elasticsearch:
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    host: elasticsearch-master.elastic-system.svc.cluster.local
    index_name: core-com-api-dev
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: elasticsearch-master-credentials
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    suppress_type_name: true
    user: elastic
