---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow-core-com-api-dev
  namespace: elastic-system
spec:
  filters:
  - detectExceptions:
      multiline_flush_interval: "0.1"
  - parser:
      parse:
        type: json
      remove_key_name_field: false
      reserve_data: true
  localOutputRefs:
  - output-core-com-api-dev
  match:
  - select:
      labels:
        app.kubernetes.io/name: host-tailer
  outputRefs:
  - output-core-com-api-dev
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: app-log-flow
  namespace: ns-app-core-dev
spec:
  filters:
  - stdout:
      output_type: json
  - detectExceptions:
      multiline_flush_interval: "0.1"
  - parser:
      parse:
        type: json
      remove_key_name_field: false
      reserve_data: true
  localOutputRefs:
  - es-output
  - s3-output
  match:
  - select:
      labels:
        tier: backend
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: output-core-com-api-dev
  namespace: elastic-system
spec:
  elasticsearch:
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    host: elasticsearch-master.elastic-system.svc.cluster.local
    index_name: app-dev-host
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: elasticsearch-master-credentials
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    suppress_type_name: true
    user: elastic
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: es-output
  namespace: ns-app-core-dev
spec:
  elasticsearch:
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    host: elasticsearch-master.elastic-system.svc.cluster.local
    index_name: core-dev
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: elasticsearch-master-credentials
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    user: elastic
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: s3-output
  namespace: ns-app-core-dev
spec:
  s3:
    aws_key_id:
      valueFrom:
        secretKeyRef:
          key: access_key_id
          name: s3-auth
    aws_sec_key:
      valueFrom:
        secretKeyRef:
          key: secret_access_key
          name: s3-auth
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    force_path_style: "true"
    path: app-log/${tag}/%Y/%m/%d/
    s3_bucket: hro-app-log
    s3_endpoint: https://kr.object.private.fin-ncloudstorage.com
    s3_region: kr-standard
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: app-logging-dev
spec:
  controlNamespace: elastic-system
  fluentbit:
    image:
      imagePullSecrets:
      - name: hero-reg
      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/fluent/fluent-bit
      tag: 2.1.4
  fluentd:
    configReloaderImage:
      imagePullSecrets:
      - name: hero-reg
      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/kube-logging/config-reloader
      tag: v0.0.5
    image:
      imagePullSecrets:
      - name: hero-reg
      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/kube-logging/fluentd
      tag: v1.15-ruby3
    logLevel: debug
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: kihoon-dev
spec:
  controlNamespace: elastic-system
  fluentbit:
    image:
      imagePullSecrets:
      - name: hero-reg
      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/fluent/fluent-bit
      tag: 2.1.4
    inputTail:
      Docker_Mode: "Off"
      Path: /hro/nas_dev/dev/hro_app/core-com-api-dev/log/core-com-api-dev-*-error.log
      multiline.parser:
      - java
    logLevel: debug
    security:
      podSecurityContext:
        runAsNonRoot: false
        runAsUser: 0
  fluentd:
    configReloaderImage:
      imagePullSecrets:
      - name: hero-reg
      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/kube-logging/config-reloader
      tag: v0.0.5
    image:
      imagePullSecrets:
      - name: hero-reg
      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/kube-logging/fluentd
      tag: v1.15-ruby3
    logLevel: debug
