--- 
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: app-logging-dev
spec:
  fluentbit: 
    image:
      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/fluent/fluent-bit
      tag: 2.1.4
  fluentd:
    image:
      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/kube-logging/fluentd
      tag: v1.15-ruby3
    logLevel: debug
    configReloaderImage:
      repository: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/elastic-system/kube-logging/config-reloader
      tag: v0.0.5
  controlNamespace: elastic-system
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: es-output
spec:
  elasticsearch:
    host: elasticsearch-master.elastic-system.svc.cluster.local
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    user: elastic
    password:
      valueFrom:
        secretKeyRef:
          name: elasticsearch-master-credentials
          key: password
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: app-log-flow
spec:
  filters:
    - parser:
        remove_key_name_field: false
        reserve_data: true
        parse:
          type: json
  match:
     - select:
         labels:
           tier: backend
  localOutputRefs:
    - es-output
    - s3-output
---
apiVersion: v1
data:
  password: Zkw3UHFPRWM4YmpNcnQxYQ==
  username: ZWxhc3RpYw==
kind: Secret
metadata:
  name: elasticsearch-master-credentials
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: s3-output
spec:
  s3:
    aws_key_id:
      valueFrom:
        secretKeyRef:
          key: access_key_id
          name: s3-auth
    aws_sec_key:
      valueFrom:
        secretKeyRef:
          key: secret_access_key
          name: s3-auth
    force_path_style: 'true'
    path: app-log/${tag}/%Y/%m/%d/
    s3_bucket: hro-app-log
    s3_endpoint: https://kr.object.private.fin-ncloudstorage.com
    s3_region: kr-standard
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
---
apiVersion: v1
data:
  access_key_id: Qjg3MDZBNjlCN0U0MUNFOTc4QUI=
  secret_access_key: N0M0OEJENDFDNjc5OTNBRDhCNjkzQTZCMzM1RUZCNkUyNzkyMUFBNA==
kind: Secret
metadata:
  name: s3-auth
type: Opaque
