global:
  imageRegistry: "tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/devops"
  imagePullSecrets: [ "hero-reg" ]
  storageClass: "nfs-client"

ingress:
  enabled: false
  path: /
  pathType: ImplementationSpecific
  hostname: rabbitmq.local
  tls: false
  ingressClassName: ""
  existingSecret: ""
