global:
  imageRegistry: "tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/devops"
  imagePullSecrets: [ "hero-reg" ]
  storageClass: "nks-block-storage"

ingress:
  enabled: false
  path: /
  pathType: ImplementationSpecific
#  hostname: rabbitmq.local
  hostname: rabbitmq.herosonsa.co.kr
  tls: true
  ingressClassName: "nginx"
  existingSecret: hro-tls-secret
replicaCount: 3
