apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dev-app-channel-hro-prm-backend-pipeline-
  labels:
    app: devops
    build-stage: dev
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
          name: app-channel-hro-prm-backend
  params:
  - name: build-stage
    value: "dev"
  - name: git-url
    value: "https://gitlab.herosonsa.co.kr/app/channel/hro-prm-backend.git"
  - name: git-revision
    value: "dev"
  - name: git-username
    value: "tekton-dashboard"
  - name: clone-to-directory
    value: $(context.pipelineRun.name)
  - name: image-url
    value: "tbd5d1uh.private-ncr.fin-ntruss.com/app/dev/channel/hro-prm-backend"
  - name: spring-profile
    value: "dev"
  - name: gitops-url
    value: "https://hello-3031818.devtools.fin-ncloud.com/3031818/hro-apps-repository.git"
  - name: gitops-revision
    value: "dev"
  - name: gitops-path
    value: "app/channel/hro-prm-backend/dev"
  - name: rollout-strategy
    value: "rolling"
  - name: deploy-manifest
    value: "kustomization.yaml"
  - name: sonar-project-key
    value: "channel-prm-api-dev"
  - name: pipeline-name
    value: $(context.pipelineRun.name)
  - name: mm-channel
    value: "chl:hro-prm-backend"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-app-channel-hro-prm-backend
  - name: gitops
    emptyDir: {}
  - name: manifest-dir
    emptyDir: {}



