---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero
  namespace: velero
automountServiceAccountToken: true
imagePullSecrets:
  - name: hero-reg
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-rbac
subjects:
  - kind: ServiceAccount
    name: velero
    namespace: velero
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: velero
  name: velero-pod
spec:
  selector:
    matchLabels:
      app: velero-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: velero-pod
    spec:
      serviceAccount: velero
      serviceAccountName: velero
      containers:
      - name: velero-pod
        image: tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/devops/dev:v2
        imagePullPolicy: IfNotPresent
        command:
          - /bin/zsh
        stdin: true
        tty: true
        env:
          - name: TZ
            value: Asia/Seoul
