global:
  imageRegistry: "tbd5d1uh.private-ncr.fin-ntruss.com/k8s/dev/devops"
  imagePullSecrets: 
    - name: hero-reg

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: redmine.herosonsa.co.kr
  path: /

## @param databaseType Redmine database type. Allowed values: `mariadb` and `postgresql`
## ref: https://github.com/bitnami/containers/tree/main/bitnami/redmine/#environment-variables
##
databaseType: postgresql
##
mariadb:
  enabled: true
  auth:
    password: bn_redmine

postgresql:
  enabled: false
  auth:
    password: bn_redmine
