global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

image:
  registry: docker.io
  repository: bitnami/redmine
  tag: 4.2.5

redmineUsername: user
redminePassword: "password"

service:
  type: ClusterIP
  ports:
    http: 80

ingress:
  enabled: true
  ingressClassName: "nginx"
  pathType: ImplementationSpecific
  hostname: redmine.herosonsa.co.kr
  path: /
  tls: false

databaseType: mariadb
mariadb:
  enabled: true
  auth:
    rootPassword: ""
    username: bn_redmine
    password: ""
    existingSecret: ""
  architecture: standalone

postgresql:
  enabled: false
